apiVersion: v1
kind: Service
metadata:
  name: micomunapp-api
  labels:
    app: micomunapp-api
spec:
  type: ClusterIP
  selector:
    app: micomunapp-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
